services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Domain\Service\ApplicationServer\ApplicationServerLifecycleServiceCollection:
    public: true

  ivoz.lifecycle.application_server.service_collection:
    '@Ivoz\Domain\Service\ApplicationServer\ApplicationServerLifecycleServiceCollection'

  ##################################
  ## post_persist
  ##################################
  Kam\Domain\Service\Dispatcher\UpdateByApplicationServer:
    tags:
      - { name: ivoz.lifecycle.application_server.post_persist, priority: 10}
    arguments:
      $entityPersister:
        '@Core\Infrastructure\Domain\Service\DoctrineEntityPersister'
      $dispatcherRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Kam\\Domain\\Model\\Dispatcher\\Dispatcher")'

  Ivoz\Domain\Service\ApplicationServer\PersistedSendXmlRcp:
    tags:
      - { name: ivoz.lifecycle.application_server.post_persist, priority: 20 }

  ##################################
  ## post_remove
  ##################################

  Ivoz\Domain\Service\ApplicationServer\RemovedSendXmlRcp:
    tags:
      - { name: ivoz.lifecycle.application_server.post_remove, priority: 10 }
