services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Domain\Service\Brand\BrandLifecycleServiceCollection:
    public: true

  ivoz.lifecycle.brand.service_collection:
    '@Ivoz\Domain\Service\Brand\BrandLifecycleServiceCollection'

  ##################################
  ## pre_persist
  ##################################
  Ivoz\Domain\Service\Brand\SanitizeEmptyValues:
    tags:
      - { name: ivoz.lifecycle.brand.pre_persist, priority: 10 }

  ##################################
  ## post_persist
  ##################################
  Ivoz\Domain\Service\Domain\UpdateByBrand:
    tags:
      - { name: ivoz.lifecycle.brand.post_persist, priority: 10 }
    arguments:
      $domainRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ivoz\\Domain\\Model\\Domain\\Domain")'

  Kam\Domain\Service\UsersDomainAttr\UpdateByBrand:
    tags:
      - { name: ivoz.lifecycle.brand.post_persist, priority: 20 }
    arguments:
      $entityPersister:
        '@Core\Infrastructure\Domain\Service\DoctrineEntityPersister'
      $usersDomainAttrRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Kam\\Domain\\Model\\UsersDomainAttr\\UsersDomainAttr")'

  Ivoz\Domain\Service\RoutingPatternGroup\UpdateByBrand:
    tags:
      - { name: ivoz.lifecycle.brand.post_persist, priority: 30 }
    arguments:
      $routingPatternGroupRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ivoz\\Domain\\Model\\RoutingPatternGroup\\RoutingPatternGroup")'
      $countryRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ivoz\\Domain\\Model\\Country\\Country")'

  Ivoz\Domain\Service\Brand\PersistedSendXmlRcp:
    tags:
      - { name: ivoz.lifecycle.brand.post_persist, priority: 40 }

  ##################################
  ## post_remove
  ##################################

  Ivoz\Domain\Service\Brand\RemovedSendXmlRcp:
    tags:
      - { name: ivoz.lifecycle.brand.post_remove, priority: 10 }