services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Domain\Service\ConferenceRoom\ConferenceRoomLifecycleServiceCollection:
    public: true

  ivoz.lifecycle.conference_room.service_collection:
    '@Ivoz\Domain\Service\ConferenceRoom\ConferenceRoomLifecycleServiceCollection'

  ##################################
  ## pre_persist
  ##################################
  Ivoz\Domain\Service\ConferenceRoom\SanitizeValues:
    tags:
      - { name: ivoz.lifecycle.conference_room.pre_persist, priority: 10 }
