services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Domain\Service\DDI\DDILifecycleServiceCollection:
    public: true

  ivoz.lifecycle.ddi.service_collection:
    '@Ivoz\Domain\Service\DDI\DDILifecycleServiceCollection'

  ##################################
  ## pre_persist
  ##################################
  Ivoz\Domain\Service\DDI\SanitizeValues:
    tags:
      - { name: ivoz.lifecycle.ddi.pre_persist, priority: 10 }
