services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Domain\Service\Domain\DomainLifecycleServiceCollection:
    public: true

  ivoz.lifecycle.domain.service_collection:
    '@Ivoz\Domain\Service\Domain\DomainLifecycleServiceCollection'

  ##################################
  ## post_persist
  ##################################

  Ivoz\Infrastructure\Domain\Service\Domain\PersistedSendXmlRpc:
    tags:
      - { name: ivoz.lifecycle.domain.post_persist, priority: 10 }

  ##################################
  ## post_remove
  ##################################

  Ivoz\Infrastructure\Domain\Service\Domain\RemovedSendXmlRpc:
    tags:
      - { name: ivoz.lifecycle.domain.post_remove, priority: 10 }
