services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Domain\Service\Fax\FaxLifecycleServiceCollection:
    public: true

  ivoz.lifecycle.fax.service_collection:
    '@Ivoz\Domain\Service\Fax\FaxLifecycleServiceCollection'

  ##################################
  ## pre_persist
  ##################################
  Ivoz\Domain\Service\Fax\SanitizeValues:
    tags:
      - { name: ivoz.lifecycle.fax.pre_persist, priority: 10}
