services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Domain\Service\HuntGroup\HuntGroupLifecycleServiceCollection:
    public: true

  ivoz.lifecycle.hunt_group.service_collection:
    '@Ivoz\Domain\Service\HuntGroup\HuntGroupLifecycleServiceCollection'

  ##################################
  ## pre_persist
  ##################################
  Ivoz\Domain\Service\HuntGroup\SanitizeValues:
    tags:
      - { name: ivoz.lifecycle.hunt_group.pre_persist, priority: 20}
