services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Domain\Service\InvoiceTemplate\InvoiceTemplateLifecycleServiceCollection:
    public: true

  ivoz.lifecycle.invoice_template.service_collection:
    '@Ivoz\Domain\Service\InvoiceTemplate\InvoiceTemplateLifecycleServiceCollection'

  ##################################
  ## pre_persist
  ##################################
  Ivoz\Domain\Service\InvoiceTemplate\CheckValidity:
    tags:
      - { name: ivoz.lifecycle.invoice_template.pre_persist, priority: 10 }