services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Domain\Service\IvrCommon\IvrCommonLifecycleServiceCollection:
    public: true

  ivoz.lifecycle.ivr_common.service_collection:
    '@Ivoz\Domain\Service\IvrCommon\IvrCommonLifecycleServiceCollection'

  ##################################
  ## pre_persist
  ##################################
  Ivoz\Domain\Service\IvrCommon\SanitizeValues:
    tags:
      - { name: ivoz.lifecycle.ivr_common.pre_persist, priority: 10 }
    arguments: ~
