services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Domain\Service\Locution\LocutionLifecycleServiceCollection:
    public: true

  ivoz.lifecycle.locution.service_collection:
    '@Ivoz\Domain\Service\Locution\LocutionLifecycleServiceCollection'

  ##################################
  ## pre_persist
  ##################################
  Ivoz\Domain\Service\Locution\SanitizeValues:
    tags:
      - { name: ivoz.lifecycle.locution.pre_persist, priority: 10 }
    arguments: ~
