services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Domain\Service\QueueMember\QueueMemberLifecycleServiceCollection:
    public: true

  ivoz.lifecycle.queue_member.service_collection:
    '@Ivoz\Domain\Service\QueueMember\QueueMemberLifecycleServiceCollection'

  ##################################
  ## post_persist & post_remove
  ##################################
  Ast\Domain\Service\QueueMember\UpdateByIvozQueueMember:
    tags:
      - { name: ivoz.lifecycle.queue_member.post_persist, priority: 10 }
    arguments:
      $entityPersister:
        '@Core\Infrastructure\Domain\Service\DoctrineEntityPersister'
      $astQueueMemberRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ast\\Domain\\Model\\QueueMember\\QueueMember")'
