services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Domain\Service\Queue\QueueLifecycleServiceCollection:
    public: true

  ivoz.lifecycle.queue.service_collection:
    '@Ivoz\Domain\Service\Queue\QueueLifecycleServiceCollection'

  ##################################
  ## pre_persist
  ##################################
  Ivoz\Domain\Service\Queue\SanitizeValues:
    tags:
      - { name: ivoz.lifecycle.queue.pre_persist, priority: 10 }
    arguments: ~

  ##################################
  ## post_persist
  ##################################
  Ast\Domain\Service\Queue\UpdateByIvozQueue:
    tags:
      - { name: ivoz.lifecycle.queue.post_persist, priority: 10 }
    arguments:
      $entityPersister:
        '@Core\Infrastructure\Domain\Service\DoctrineEntityPersister'
      $astQueueRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ast\\Domain\\Model\\Queue\\Queue")'