services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Domain\Service\RetailAccount\RetailAccountLifecycleServiceCollection:
    public: true

  ivoz.lifecycle.retail_account.service_collection:
    '@Ivoz\Domain\Service\RetailAccount\RetailAccountLifecycleServiceCollection'

  ##################################
  ## pre_persist
  ##################################
  Ivoz\Domain\Service\RetailAccount\SanitizeValues:
    tags:
      - { name: ivoz.lifecycle.retail_account.pre_persist, priority: 10 }
    arguments: ~

  ##################################
  ## post_persist
  ##################################
  Ast\Domain\Service\PsEndpoint\UpdateByRetailAccount:
    tags:
      - { name: ivoz.lifecycle.retail_account.post_persist, priority: 10 }
    arguments:
      $entityPersister:
        '@Core\Infrastructure\Domain\Service\DoctrineEntityPersister'
      $psEndpointRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ast\\Domain\\Model\\PsEndpoint\\PsEndpoint")'

  Ast\Domain\Service\PsAor\UpdateByRetailAccount:
    tags:
      - { name: ivoz.lifecycle.retail_account.post_persist, priority: 10 }
    arguments:
      $entityPersister:
        '@Core\Infrastructure\Domain\Service\DoctrineEntityPersister'
      $psAorRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ast\\Domain\\Model\\PsAor\\PsAor")'
      $psEndpointRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ast\\Domain\\Model\\PsEndpoint\\PsEndpoint")'