services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Domain\Service\RoutingPattern\RoutingPatternLifecycleServiceCollection:
    public: true

  ivoz.lifecycle.routing_pattern.service_collection:
    '@Ivoz\Domain\Service\RoutingPattern\RoutingPatternLifecycleServiceCollection'

  ##################################
  ## post_persist
  ##################################
  Ivoz\Domain\Service\LcrRule\UpdateByRoutingPattern:
    tags:
      - { name: ivoz.lifecycle.routing_pattern.post_persist, priority: 10}
    arguments:
      $entityPersister:
        '@Core\Infrastructure\Domain\Service\DoctrineEntityPersister'

  Ivoz\Infrastructure\Domain\Service\RoutingPattern\PersistedSendXmlRpc:
    tags:
      - { name: ivoz.lifecycle.routing_pattern.post_persist, priority: 20 }

  ##################################
  ## post_remove
  ##################################
  Ivoz\Infrastructure\Domain\Service\RoutingPattern\RemovedSendXmlRpc:
    tags:
      - { name: ivoz.lifecycle.routing_pattern.post_remove, priority: 10 }
