services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Domain\Service\TransformationRulesetGroupsTrunk\TransformationRulesetGroupsTrunkLifecycleServiceCollection:
    public: true

  ivoz.lifecycle.transformation_ruleset_groups_trunk.service_collection:
    '@Ivoz\Domain\Service\TransformationRulesetGroupsTrunk\TransformationRulesetGroupsTrunkLifecycleServiceCollection'

  ##################################
  ## pre_persist
  ##################################
  Kam\Domain\Service\TrunksDialplan\CreateCalleeOutRules:
    tags:
      - { name: ivoz.lifecycle.transformation_ruleset_groups_trunk.pre_persist, priority: 10 }
    arguments:
      $entityPersister:
        '@Core\Infrastructure\Domain\Service\DoctrineEntityPersister'

  Kam\Domain\Service\TrunksDialplan\CreateCallerOutRules:
    tags:
      - { name: ivoz.lifecycle.transformation_ruleset_groups_trunk.pre_persist, priority: 20 }
    arguments:
      $entityPersister:
        '@Core\Infrastructure\Domain\Service\DoctrineEntityPersister'

  Kam\Domain\Service\TrunksDialplan\CreateCalleeInRules:
    tags:
      - { name: ivoz.lifecycle.transformation_ruleset_groups_trunk.pre_persist, priority: 30 }
    arguments:
      $entityPersister:
        '@Core\Infrastructure\Domain\Service\DoctrineEntityPersister'

  Kam\Domain\Service\TrunksDialplan\CreateCallerInRules:
    tags:
      - { name: ivoz.lifecycle.transformation_ruleset_groups_trunk.pre_persist, priority: 40 }
    arguments:
      $entityPersister:
        '@Core\Infrastructure\Domain\Service\DoctrineEntityPersister'

  ##################################
  ## post_remove
  ##################################
  Ivoz\Infrastructure\Domain\Service\TransformationRulesetGroupsTrunk\RemovedSendXmlRpc:
    tags:
      - { name: ivoz.lifecycle.peer_server.post_remove, priority: 10 }
