#include conf.d/mapperList.yaml
#include conf.d/actions.yaml
#include IvrCustomEntriesList.yaml

production:
  main:
    module: klearMatrix
    defaultScreen: IvrCustomList_screen
  screens:
    IvrCustomList_screen: &IvrCustomList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *IvrCustom
      title: _("List of %s %2s", ngettext('IVR Custom', 'IVRs Custom', 0), "[format| (%parent%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        order:
          name: true
          timeout: true
          noAnswerTimeout: true
          timeoutTargetType: true
          timeoutTarget: true
          errorTargetType: true
          errorTarget: true
        blacklist:
          maxDigits: true
          welcomeLocution: true
          noAnswerLocution: true
          errorLocution: true
          successLocution: true
          timeoutNumberValue: true
          timeoutExtension: true
          timeoutVoiceMailUser: true
          errorNumberValue: true
          errorExtension: true
          errorVoiceMailUser: true
        options:
          title: _("Options")
          screens:
            IvrCustomEdit_screen: true
            IvrCustomEntriesList_screen: true
          dialogs:
            IvrCustomDel_dialog: true
          default: IvrCustomEdit_screen
      options:
        title: _("Options")
        screens:
          IvrCustomNew_screen: true
        dialogs:
          IvrCustomDel_dialog: true
    IvrCustomNew_screen: &IvrCustomNew_screenLink
      <<: *IvrCustom
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('IVR Custom', 'IVRs Custom', 1))
      shortcutOption: N
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist:
          noAnswerTarget: true
          errorTarget: true
          timeoutTarget : true
      fixedPositions: &IvrCustomFixedPositions_link
        group0:
          label: _("Basic Configuration")
          colsPerRow: 12
          fields:
            name: 4
            timeout: 4
            maxDigits: 4
            welcomeLocution: 6
            successLocution: 6
        group1:
          label: _("No answer configuration")
          colsPerRow: 3
          fields:
            noAnswerLocution: 2
            noAnswerTimeout: 1
            timeoutTargetType: 1
            timeoutNumberValue: 1
            timeoutExtension: 1
            noAnswerUser: 1
            timeoutVoiceMailUser: 1
        group2:
          label: _("Error configuration")
          colsPerRow: 6
          fields:
            ErrorLocution: 5
            errorTargetType: 2
            errorNumberValue: 2
            errorExtension: 2
            errorUser: 2
            errorVoiceMailUser: 2
    IvrCustomEdit_screen: &IvrCustomEdit_screenLink
      <<: *IvrCustom
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('IVR Custom', 'IVRs Custom', 1), "[format| (%item%)]")
      forcedValues:
        <<: *forcedCompany
      fields:
        blacklist:
          noAnswerTarget: true
          errorTarget: true
          timeoutTarget: true
      fixedPositions:
        <<: *IvrCustomFixedPositions_link
    #IVRCustomEntries
    <<: *IvrCustomEntries_screensLink
    IvrCustomEntriesList_screen:
      <<: *IvrCustomEntriesList_screenLink
      filterField: IvrCustom
      parentOptionCustomizer:
        - recordCount
    IvrCustomEntriesNew_screen:
      <<: *IvrCustomEntriesNew_screenLink
      filterField: IvrCustom
    IvrCustomEntriesEdit_screen:
      <<: *IvrCustomEntriesEdit_screenLink
      filterField: IvrCustom
  dialogs:
    IvrCustomDel_dialog: &IvrCustomDel_dialogLink
      <<: *IvrCustom
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('IVR Custom', 'IVRs Custom', 1))
      description: _("Do you want to delete this %s?", ngettext('IVR Custom', 'IVRs Custom', 1))
      message: _("%s successfully deleted.", ngettext('IVR Custom', 'IVRs Custom', 1))
      multiItem: 1
      labelOnList: 1
    #IVRCustomEntries
    <<: *IvrCustomEntries_dialogsLink
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
