#include conf.d/mapperList.yaml
#include conf.d/actions.yaml


production:
  main:
    module: klearMatrix
    defaultScreen: kamUsersAddressList_screen
  screens: &kamUsersAddress_screensLink
    kamUsersAddressList_screen: &kamUsersAddressList_screenLink
      controller: list
      pagination:
        items: 25
      <<: *KamUsersAddress
      class: ui-silk-door-in
      title: _("List of %s %2s", ngettext('Authorized source', 'Authorized sources', 0), "[format| (%parent%)]")
      fields: &kamUsersAddress_fieldsLink
        blacklist: &kamUsersAddress_blacklistLink
          grp: true
          ipAddr: true
          mask: true
          port: true
          tag: true
        options:
          title: _("Options")
          screens:
            kamUsersAddressEdit_screen: true
          dialogs:
            kamUsersAddressDel_dialog: true
          default: kamUsersAddressEdit_screen
      info: &kamUsersAddress_helpLink
        type: tooltip
        position: left
        icon: error
        label:
          "Enable IP filter in Companies settings to apply. If enabled and no address set, all calls will be rejected."
      options:
        title: _("Options")
        screens:
          kamUsersAddressNew_screen: true
        dialogs:
          kamUsersAddressDel_dialog: true
    kamUsersAddressNew_screen: &kamUsersAddressNew_screenLink
      <<: *KamUsersAddress
      controller: new
      class: ui-silk-add
      fields:
        blacklist:
          <<: *kamUsersAddress_blacklistLink
      info:
          <<: *kamUsersAddress_helpLink
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Authorized source', 'Authorized sources', 1), "[format| (%parent%)]")
      shortcutOption: N
    kamUsersAddressEdit_screen: &kamUsersAddressEdit_screenLink
      <<: *KamUsersAddress
      controller: edit
      class: ui-silk-pencil
      fields:
        blacklist:
          <<: *kamUsersAddress_blacklistLink
      info:
          <<: *kamUsersAddress_helpLink
      label: false
      labelOnPostAction: _("Edit %s %2s", ngettext('Authorized source', 'Authorized sources', 1), "[format| (%item%)]")
      title: _("Edit %s %2s", ngettext('Authorized source', 'Authorized sources', 1), "[format| (%item%)]")
  dialogs: &kamUsersAddress_dialogsLink
    kamUsersAddressDel_dialog: &kamUsersAddressDel_dialogLink
      <<: *KamUsersAddress
      controller: delete
      class: ui-silk-bin
      fields:
        blacklist:
          <<: *kamUsersAddress_blacklistLink
      labelOption: false
      title: _("Delete %s", ngettext('Authorized source', 'Authorized sources', 1))
      description: _("Do you want to delete this %s?", ngettext('Authorized source', 'Authorized sources', 1))
      message: _("%s successfully deleted.", ngettext('Authorized source', 'Authorized sources', 1))
      multiItem: 1
      labelOnList: 1
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
