services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Kam\Domain\Service\AccCdr\AccCdrLifecycleServiceCollection:
    public: true

  kam.lifecycle.acc_cdr.service_collection:
    '@Kam\Domain\Service\AccCdr\AccCdrLifecycleServiceCollection'

  ##################################
  ## pre_persist
  ##################################
  Kam\Domain\Service\AccCdr\SanitizeValues:
    tags:
      - { name: kam.lifecycle.acc_cdr.pre_persist, priority: 10 }
    arguments: ~
