services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Kam\Domain\Service\PikeTrusted\PikeTrustedLifecycleServiceCollection:
    public: true

  kam.lifecycle.pike_trusted.service_collection:
    '@Kam\Domain\Service\PikeTrusted\PikeTrustedLifecycleServiceCollection'

  ##################################
  ## pre_persist
  ##################################
  Kam\Domain\Service\PikeTrusted\CheckValidity:
    tags:
      - { name: kam.lifecycle.pike_trusted.pre_persist, priority: 10}

  ##################################
  ## post_persist
  ##################################
  Kam\Domain\Service\PikeTrusted\PersistedSendXmlRcp:
    tags:
      - { name: kam.lifecycle.pike_trusted.post_persist, priority: 10 }

  ##################################
  ## post_remove
  ##################################
  Kam\Domain\Service\PikeTrusted\RemovedSendXmlRcp:
    tags:
      - { name: kam.lifecycle.pike_trusted.post_remove, priority: 10 }
