services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Kam\Domain\Service\Rtpproxy\RtpproxyLifecycleServiceCollection:
    public: true

  kam.lifecycle.rtpproxy.service_collection:
    '@Kam\Domain\Service\Rtpproxy\RtpproxyLifecycleServiceCollection'

  ##################################
  ## pre_persist
  ##################################
  Kam\Domain\Service\Rtpproxy\SanitizeValues:
    tags:
      - { name: kam.lifecycle.rtpproxy.pre_persist, priority: 10 }
    arguments: ~

