services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Kam\Domain\Service\TrunksDialplan\TrunksDialplanLifecycleServiceCollection:
    public: true

  kam.lifecycle.trunks_dialplan.service_collection:
    '@Kam\Domain\Service\TrunksDialplan\TrunksDialplanLifecycleServiceCollection'

  ##################################
  ## pre_persist
  ##################################
  Kam\Domain\Service\TrunksDialplan\SanitizeValues:
    tags:
      - { name: kam.lifecycle.trunks_dialplan.pre_persist, priority: 10 }
    arguments: ~

  ##################################
  ## post_persist
  ##################################
  Kam\Domain\Service\TrunksDialplan\PersistedSendXmlRcp:
    tags:
      - { name: kam.lifecycle.trunks_dialplan.post_persist, priority: 10 }

  ##################################
  ## post_remove
  ##################################
  Ivoz\Domain\Service\TransformationRulesetGroupsTrunk\CleanUpByRemovedTrunksDialplan:
    tags:
      - { name: kam.lifecycle.trunks_dialplan.post_persist, priority: 10 }
    arguments:
      $transformationRepository:
        '@=service("doctrine.orm.entity_manager").getRepository("Ivoz\\Domain\\Model\\TransformationRulesetGroupsTrunk\\TransformationRulesetGroupsTrunk")'

  Kam\Domain\Service\TrunksDialplan\RemovedSendXmlRcp:
    tags:
      - { name: kam.lifecycle.trunks_dialplan.post_remove, priority: 20 }