services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Kam\Domain\Service\UsersAddress\UsersAddressLifecycleServiceCollection:
    public: true

  kam.lifecycle.acc_cdr.service_collection:
    '@Kam\Domain\Service\UsersAddress\UsersAddressLifecycleServiceCollection'

  ##################################
  ## pre_persist
  ##################################
  Kam\Domain\Service\UsersAddress\CheckValidityAndSanitizeValues:
    tags:
      - { name: kam.lifecycle.users_address.pre_persist, priority: 10 }
    arguments: ~

  ##################################
  ## post_persist
  ##################################
  Kam\Infrastructure\Domain\Service\UsersAddress\PersistedSendXmlRpc:
    tags:
      - { name: kam.lifecycle.trunks_uacreg.post_persist, priority: 10 }

  ##################################
  ## post_remove
  ##################################
  Kam\Infrastructure\Domain\Service\UsersAddress\RemovedSendXmlRpc:
    tags:
      - { name: kam.lifecycle.trunks_uacreg.post_remove, priority: 10 }