production:
  class: \IvozProvider\Model\CallACLRelPatterns
  dto: Core\Application\DTO\CallACLRelPatternDTO
  entity: Core\Model\CallACLRelPattern\CallACLRelPattern
  fields:
    CallACL:
      title: ngettext('Call ACL', 'Call ACLs', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\CallACL
          entity: \Core\Model\CallACL\CallACL
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            CallACL.name: asc
      default: true
    CallACLPattern:
      title: ngettext('Call ACL Pattern', 'Call ACL Patterns', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\CallACLPatterns
          entity: \Core\Model\CallACLPattern\CallACLPattern
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            CallACLPattern.name: asc
    priority:
      title: _('Priority')
      type: number
      required: true
      source:
        control: Spinner
    policy:
      title: _('Policy')
      type: select
      required: true
      source:
        data: inline
        values:
          'allow': _('allow')
          'deny': _('deny')
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
