production: 
  class: \IvozProvider\Model\FeaturesRelCompanies
  entity: Ivoz\Domain\Model\FeaturesRelCompany\FeaturesRelCompany
  fields: 
    companyId:
      title: _('Companyid')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Companies
          entity: \Ivoz\Domain\Model\Company\Company
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Company.name: asc
      default: true
    featureId:
      title: _('Featureid')
      type: select
      required: true
      source: 
        data: mapper
        config: 
#          mapperName: \IvozProvider\Mapper\Sql\Features
          entity: \Ivoz\Domain\Model\Terminal\Feature\Feature
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order:
            Feature.name: asc
staging: 
  _extends: production
testing: 
  _extends: production
development: 
  _extends: production
localdev: 
  _extends: production
