production:
  class: \IvozProvider\Model\FriendsPatterns
  dto: Core\Application\DTO\FriendsPatternDTO
  entity: Core\Model\FriendsPattern\FriendsPattern
  fields: 
    friend:
      title: ngettext('Friend', 'Friends', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Friends
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Friends.name: asc
      default: true
    name:
      title: _('Name')
      type: text
      required: true
      maxLength: 50
    regExp:
      title: _('Regular Expression')
      type: text
      required: true
      maxLength: 255
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
