production:
  class: \IvozProvider\Model\IVRCommon
  dto: Core\Application\DTO\IVRCommonDTO
  entity: Core\Model\IVRCommon\IVRCommon
  fields:
    companyId:
      title: ngettext('Company', 'Companies', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Companies
          entity: \Core\Model\Company\Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Company.name: asc
      default: true
    name:
      title: _('Name')
      type: text
      trim: both
      required: true
    blackListRegExp:
      title: _('Black list reg exp')
      type: text
      trim: both
    welcomeLocutionId:
      title: _('Welcome locution')
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Locutions
          entity: \Core\Model\Locution\Locution
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Locution.name: asc
    noAnswerLocutionId:
      title: _('No answer locution')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Locutions
          entity: \Core\Model\Locution\Locution
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Locution.name: asc
        'null': _("Unassigned")
    errorLocutionId:
      title: ngettext('Locution', 'Locutions', 1)
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Locutions
          entity: \Core\Model\Locution\Locution
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Locution.name: asc
        'null': _("Unassigned")
    successLocutionId:
      title: _('Success locution')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Locutions
          entity: \Core\Model\Locution\Locution
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Locution.name: asc
        'null': _("Unassigned")
    timeout:
      title: _('Timeout')
      type: number
      required: true
      defaultValue: 6
      source:
        control: spinner
        max: 60
        min: 1
      info:
        type: box
        position: left
        icon: help
        text: _("Time in seconds the IVR will wait after playing the welcome locution or dialing a digit")
        label: _("Need help?")
    maxDigits:
      title: _('Max digits')
      type: number
      required: true
      defaultValue: 0
      source:
        control: Spinner
        min: 0
      info:
        type: box
        position: left
        icon: help
        text: _("Max number of digits the caller can enter. Set to 0 to disable.")
        label: _("Need help?")
    noAnswerTimeout:
      title: _('No answer timeout')
      type: number
      defaultValue: 10
      source:
        control: Spinner
    timeoutTargetType:
      title: _('Timeout target type')
      type: select
      source:
        data: inline
        values:
          '__null__':
            title: _('Unassigned')
            visualFilter:
              hide: ["timeoutNumberValue", "timeoutExtensionId", "timeoutVoiceMailUserId" ]
          'number':
            title: _('Number')
            visualFilter:
              show: ["timeoutNumberValue"]
              hide: ["timeoutExtensionId", "timeoutVoiceMailUserId" ]
          'extension':
            title: ngettext('Extension', 'Extensions', 1)
            visualFilter:
              show: ["timeoutExtensionId"]
              hide: ["timeoutNumberValue", "timeoutVoiceMailUserId" ]
          'voicemail':
            title: ngettext('Voicemail', 'Voicemails', 1)
            visualFilter:
              show: ["timeoutVoiceMailUserId"]
              hide: ["timeoutExtensionId", "timeoutNumberValue"]
    timeoutNumberValue:
      title: _('Number')
      type: text
      trim: both
      required: true
    timeoutExtensionId:
      title: ngettext('Extension', 'Extensions', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Extensions
          entity: \Core\Model\Extension\Extension
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - number
            template: '%number%'
          order:
            Extension.number: asc
        'null': _("Unassigned")
    timeoutVoiceMailUserId:
      title: ngettext('Voicemail', 'Voicemails', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Users
          entity: \Core\Model\User\User
          filterclass: IvozProvider_Klear_Filter_Voicemail
          fieldName:
            fields:
              - name
              - lastname
            template: '%name% %lastname%'
          order:
            User.name: asc
        'null': _("Unassigned")
    errorTargetType:
      title: _('Error target type')
      type: select
      source:
        data: inline
        values:
          '__null__':
            title: _('Unassigned')
            visualFilter:
              hide: ["errorNumberValue", "errorExtensionId", "errorVoiceMailUserId" ]
          'number':
            title: _('Number')
            visualFilter:
              show: ["errorNumberValue"]
              hide: ["errorExtensionId", "errorVoiceMailUserId" ]
          'extension':
            title: ngettext('Extension', 'Extensions', 1)
            visualFilter:
              show: ["errorExtensionId"]
              hide: ["errorNumberValue", "errorVoiceMailUserId" ]
          'voicemail':
            title: ngettext('Voicemail', 'Voicemails', 1)
            visualFilter:
              show: ["errorVoiceMailUserId"]
              hide: ["errorExtensionId", "errorNumberValue"]
    errorNumberValue:
      title: _('Number')
      type: text
      trim: both
      required: true
    errorExtensionId:
      title: ngettext('Extension', 'Extensions', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Extensions
          entity: \Core\Model\Extension\Extension
          filterclass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - number
            template: '%number%'
          order:
            Extension.number: asc
        'null': _("Unassigned")
    errorVoiceMailUserId:
      title: ngettext('Voicemail', 'Voicemails', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\Users
          entity: \Core\Model\User\User
          filterclass: IvozProvider_Klear_Filter_Voicemail
          fieldName:
            fields:
              - name
              - lastname
            template: '%name% %lastname%'
          order:
            User.number: asc
        'null': _("Unassigned")
    timeoutTarget:
      title: _('Timeout target')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_IVRCommonTarget
        method: getTimeoutData
    errorTarget:
      title: _('Error target')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_IVRCommonTarget
        method: getErrorData
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
