production:
  class: \IvozProvider\Model\OutgoingDDIRules
  entity: Ivoz\Domain\Model\OutgoingDDIRule\OutgoingDDIRule
  fields:
    companyId:
      title: ngettext('Company', 'Companies', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          mapperName: \IvozProvider\Mapper\Sql\Companies
          fieldName:
            fields:
              - type
            template: '%type%'
          order:
            type: asc
      default: true
    name:
      title: _('Name')
      type: text
      required: true
      maxLength: 50
    defaultAction:
      title: _('Default Action')
      type: select
      required: true
      source:
        data: inline
        values:
          'keep':
            title: _("Keep Original DDI")
            visualFilter:
              show: []
              hide: ["forcedDDIId"]
          'force':
            title: _("Force DDI")
            visualFilter:
              show: ["forcedDDIId"]
              hide: []
    forcedDDIId:
      title: _('Forced DDI')
      type: select
      source:
        data: mapper
        config:
#          mapperName: \IvozProvider\Mapper\Sql\DDIs
          entity:  \Ivoz\Domain\Model\DDI\DDI
          filterClass: IvozProvider_Klear_Filter_Company
          fieldName:
            fields:
              - ddie164
            template: '+%ddie164%'
          order:
            DDI.ddie164: asc
        'null': _("Company's default")
    forcedDDI:
      title: _('Forced DDI')
      type: ghost
      source:
        class: IvozProvider_Klear_Ghost_OutgoingRule
        method: getOutgoingRuleForcedDDI
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
