production:
  class: \IvozProvider\Model\TerminalManufacturers
  entity: Ivoz\Domain\Model\TerminalManufacturer\TerminalManufacturer
  fields: 
    iden:
      title: ngettext('Iden', 'Idens', 1)
      type: text
      trim: both
      required: true
    name:
      title: _('Name')
      type: text
      trim: both
      defaultValue:
      default: true
    description:
      title: _('Description')
      type: text
      trim: both
      defaultValue:
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
