Ivoz\Domain\Model\ConditionalRoutesCondition\ConditionalRoutesCondition:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\ConditionalRoutesConditionDoctrineRepository
  type: entity
  table: ConditionalRoutesConditions
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks: {  }
