Ivoz\Domain\Model\MatchList\MatchList:
  type: entity
  table: MatchLists
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    patterns:
      targetEntity: Ivoz\Domain\Model\MatchListPattern\MatchListPatternInterface
      mappedBy: matchList
  lifecycleCallbacks:
      postLoad:
        - initChangelog
