Ivoz\Domain\Model\PeerServer\PeerServer:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\PeerServerDoctrineRepository
  type: entity
  table: PeerServers
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    lcrGateways:
      targetEntity: Ivoz\Domain\Model\LcrGateway\LcrGatewayInterface
      mappedBy: peerServer
  lifecycleCallbacks:
    postLoad:
      - initChangelog
