Ivoz\Domain\Model\RetailAccount\RetailAccount:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\RetailAccountDoctrineRepository
  type: entity
  table: RetailAccounts
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    psEndpoints:
      targetEntity: Ast\Domain\Model\PsEndpoint\PsEndpointInterface
      mappedBy: retailAccount
    DDIs:
      targetEntity: Ivoz\Domain\Model\DDI\DDIInterface
      mappedBy: retailAccount
  lifecycleCallbacks:
    postLoad:
      - initChangelog
