Ivoz\Domain\Model\User\User:
  repositoryClass: Ivoz\Infrastructure\Persistence\Doctrine\UserDoctrineRepository
  type: entity
  table: Users
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  oneToMany:
    pickUpRelUsers:
      targetEntity: Ivoz\Domain\Model\PickUpRelUser\PickUpRelUserInterface
      mappedBy: user
    queueMembers:
      targetEntity: Ivoz\Domain\Model\QueueMember\QueueMemberInterface
      mappedBy: user
  lifecycleCallbacks:
    postLoad:
      - initChangelog
