Kam\Domain\Model\UsersAddress\UsersAddress:
  repositoryClass: Kam\Infrastructure\Persistence\Doctrine\UsersAddressDoctrineRepository
  type: entity
  table: kam_users_address
  id:
    id:
      type: integer
      nullable: false
      options:
        unsigned: true
      id: true
      generator:
        strategy: IDENTITY
  lifecycleCallbacks:
    postLoad:
      - initChangelog
