<?php

namespace Kam\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Kam\Domain\Model\UsersAddress\UsersAddressRepository;

/**
 * UsersAddressDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersAddressDoctrineRepository extends EntityRepository implements UsersAddressRepository
{
}
