<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\ConditionalRoutesConditionsRelCalendar\ConditionalRoutesConditionsRelCalendarRepository;

/**
 * ConditionalRoutesConditionsRelCalendarDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionalRoutesConditionsRelCalendarDoctrineRepository extends EntityRepository implements ConditionalRoutesConditionsRelCalendarRepository
{
}
