<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\ConditionalRoute\ConditionalRouteRepository;

/**
 * ConditionalRouteDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionalRouteDoctrineRepository extends EntityRepository implements ConditionalRouteRepository
{
}
