<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\ConditionalRoutesCondition\ConditionalRoutesConditionRepository;

/**
 * ConditionalRoutesConditionDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConditionalRoutesConditionDoctrineRepository extends EntityRepository implements ConditionalRoutesConditionRepository
{
}
