<?php

namespace Ivoz\Infrastructure\Persistence\Doctrine;

use Doctrine\ORM\EntityRepository;
use Ivoz\Domain\Model\IvrCommon\IvrCommonRepository;

/**
 * IvrCommonDoctrineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IvrCommonDoctrineRepository extends EntityRepository implements IvrCommonRepository
{
}
