imports:
  - { resource: "@CoreBundle/Resources/config/lifecycle/core/xml_rpc.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/ivoz.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/kam.yml" }

services:
  _defaults:
    autowire: true
    public: false

  Core\Infrastructure\Domain\Service\Lifecycle\DoctrineEventSubscriber:
      arguments:
        - "@service_container"
      tags:
        - { name: doctrine.event_subscriber }

  Core\Domain\Service\LifecycleEventListener:
    public: true

